import { useState } from "react";

const CATEGORY_META = {
  Reach: { color: "#FF6B35", bg: "rgba(255,107,53,0.08)", border: "rgba(255,107,53,0.25)", desc: "Viral / Discovery — naye log aayenge", icon: "🔥" },
  Trust: { color: "#00C2FF", bg: "rgba(0,194,255,0.08)", border: "rgba(0,194,255,0.25)", desc: "Authority / Depth — credibility badhegi", icon: "🧠" },
  Sales: { color: "#A259FF", bg: "rgba(162,89,255,0.08)", border: "rgba(162,89,255,0.25)", desc: "Conversion — fans ko loyal banao", icon: "💰" },
};

const FORMAT_COLORS = {
  "Short Reel": "#FF6B35", "Talking Head": "#00C2FF", "Mini Doc": "#A259FF",
  "Explainer": "#FFD700", "Series": "#00E5A0", "Voiceover B-Roll": "#FF6B35", "Storytime": "#00C2FF",
};

const DEFAULT_IDEAS = [
  { id:1, title:"India mein degree hai, job nahi — kyun?", category:"Reach", format:"Short Reel", hook:"4 saal ki mehnat, aur result? Zero job offer.", angle:"Frustrated job seeker", why:"Millions of graduates relate instantly. Viral potential high because it validates a shared pain." },
  { id:2, title:"NEET paper leak ka sach jo media nahi batata", category:"Reach", format:"Voiceover B-Roll", hook:"Yeh sirf paper leak nahi tha — yeh system ka failure tha.", angle:"Outrage + hidden truth", why:"Conspiracy + education = massive reach among students and parents." },
  { id:3, title:"Instagram pe jo dikhta hai, woh reality nahi hai", category:"Reach", format:"Talking Head", hook:"Yeh influencer 'broke' tha 6 mahine pehle.", angle:"Reality check shock", why:"Social media users feel deceived — this triggers shares and comments." },
  { id:4, title:"Kisan ki ek din ki kamai jaante ho kitni hai?", category:"Reach", format:"Voiceover B-Roll", hook:"Jo roti tum khaate ho, woh banana waale ko ₹30 milte hain poore din.", angle:"Guilt + empathy trigger", why:"Urban audience ko rural reality se connect karata hai — highly shareable." },
  { id:5, title:"Govt job ka sapna — trap hai ya reality?", category:"Reach", format:"Short Reel", hook:"10 saal preparation, 1 seat, 5 lakh candidates.", angle:"Dream vs reality clash", why:"SSC/UPSC aspirants = massive audience in India. Direct pain point." },
  { id:6, title:"Mobile addiction — yeh teri galti nahi hai", category:"Reach", format:"Explainer", hook:"Yeh app tumhe addict karne ke liye design kiya gaya hai.", angle:"Victim validation", why:"Blaming the system not the user = massive positive response + shares." },
  { id:7, title:"Dowry ban hai, fir bhi chal raha hai — kyun?", category:"Reach", format:"Mini Doc", hook:"1961 mein ban hua. 2024 mein bhi zinda hai. Kyun?", angle:"System failure shock", why:"Gender + social issues = broad audience reach across age groups." },
  { id:8, title:"Inflation ka sach — 1 figure jo sarkar nahi batati", category:"Reach", format:"Short Reel", hook:"Government kehti hai 5% inflation. Tumhara ghar kehta hai 30%.", angle:"Betrayal by authority", why:"Everyone feels inflation. This validates their experience vs official data." },
  { id:9, title:"Psychology: Log desh chhod kyun rahe hain?", category:"Reach", format:"Explainer", hook:"Har mahine 1 lakh padhe-likhe Indians desh chhod rahe hain.", angle:"National pride + fear", why:"Brain drain debate always trends. Emotional + factual combination." },
  { id:10, title:"Ek village school ki reality — camera ke saath", category:"Reach", format:"Mini Doc", hook:"Is school mein teacher hai, building hai — lekin padhne wala koi nahi.", angle:"Systemic neglect expose", why:"Rural education reality shocks urban viewers. Documentary style drives deep engagement." },
  { id:11, title:"Education system kaise broke hua — timeline", category:"Trust", format:"Explainer", hook:"1947 se 2024 tak — kab, kahan, kya galat hua.", angle:"Historical deep-dive", why:"Research-based content builds authority. UPSC audience loves timelines." },
  { id:12, title:"Gig economy ka sach — Swiggy waale ki kahani", category:"Trust", format:"Storytime", hook:"Uski degree thi, fir bhi delivery karta hai. Yeh uski galti nahi.", angle:"Dignity + system critique", why:"Personal story + economic reality = deep trust building content." },
  { id:13, title:"Loan waiver kya hai aur kisan ko fayda kyun nahi", category:"Trust", format:"Explainer", hook:"Sarkar ne ₹2 lakh crore maaf kiye. Kisan fir bhi kyun toota hai?", angle:"Policy reality gap", why:"Explains complex policy simply. Builds credibility as a reliable source." },
  { id:14, title:"Psychological trap: Hum galat news kyun share karte hain?", category:"Trust", format:"Talking Head", hook:"Tumhara brain jhooth zyada quickly believe karta hai — science bolta hai.", angle:"Self-awareness unlock", why:"Meta content about media literacy builds deep trust with aware audience." },
  { id:15, title:"Women workforce India mein kyu gir rahi hai?", category:"Trust", format:"Explainer", hook:"1990 mein 30% women working. 2024 mein 19%. Kyun?", angle:"Data-driven revelation", why:"Statistics + social issue = shareable, citable content. Builds research credibility." },
  { id:16, title:"Sarkari scheme jo kaam karti hai — honest review", category:"Trust", format:"Talking Head", hook:"Main sirf criticism nahi karta — yeh scheme actually helpful hai.", angle:"Balanced honest voice", why:"Being fair builds more trust than constant negativity. Audience respects balance." },
  { id:17, title:"Kaise ek scam poore district ko barbad kar deta hai", category:"Trust", format:"Mini Doc", hook:"Ek chit fund scheme. 5000 families. Sabka paisa gaya.", angle:"Investigative expose", why:"Real-life scam stories = high retention + shares. Builds journalistic credibility." },
  { id:18, title:"Mental health India mein — kyu log baat nahi karte?", category:"Trust", format:"Explainer", hook:"India mein 15 crore log mental illness se suffer karte hain. Sirf 3% treatment lete hain.", angle:"Stigma + system failure", why:"Sensitive topic handled with research builds deep community trust." },
  { id:19, title:"UPI ne kaise change ki rural India ki economy?", category:"Trust", format:"Explainer", hook:"Is gaon mein bank nahi tha. UPI se sab badal gaya.", angle:"Positive change documentary", why:"Positive + factual = shareable. Shows nuanced thinking beyond only criticism." },
  { id:20, title:"Why India's ranking falls every year — explained", category:"Trust", format:"Explainer", hook:"Press freedom, hunger index, happiness — hum gir kyun rahe hain?", angle:"Data over emotion", why:"Index-based content gets cited and shared heavily by UPSC/news audience." },
  { id:21, title:"Mera content journey — zero se yahan tak", category:"Sales", format:"Storytime", hook:"6 mahine pehle mujhe koi nahi jaanta tha. Aaj tum yahan ho.", angle:"Authentic origin story", why:"Personal journey builds parasocial connection — converts viewers to loyal followers." },
  { id:22, title:"Yeh 5 creators se main kyun alag hoon", category:"Sales", format:"Talking Head", hook:"Main sirf viral nahi, sach batane aaya hoon.", angle:"Differentiation positioning", why:"Positioning content turns casual viewers into committed audience members." },
  { id:23, title:"Mujhe follow karo — yeh reason hai", category:"Sales", format:"Short Reel", hook:"Har hafte ek aisi reality jo koi nahi batata.", angle:"Value promise CTA", why:"Direct value proposition. Converts view to follow when delivered authentically." },
  { id:24, title:"India ki woh reality jo main cover karunga", category:"Sales", format:"Talking Head", hook:"Yeh topics hain jo main 2025 mein expose karunga.", angle:"Future content teaser", why:"Series announcements build anticipation and long-term audience retention." },
  { id:25, title:"Agar tum UPSC/SSC aspirant ho — yeh dekho", category:"Sales", format:"Short Reel", hook:"Yeh channel tumhare GS ke liye free resource ban sakta hai.", angle:"Niche audience direct pitch", why:"Targeting a specific sub-audience converts at much higher rate than broad CTA." },
  { id:26, title:"Kya main sponsored content karunga? Honest jawab", category:"Sales", format:"Talking Head", hook:"Mujhe offer aa rahe hain. Yeh meri policy hai.", angle:"Transparency = trust", why:"Honesty about monetization paradoxically increases audience trust and support." },
  { id:27, title:"Tumhare comments ne yeh episode banwaya", category:"Sales", format:"Storytime", hook:"Tumne pucha, maine research kiya. Yeh lo jawab.", angle:"Community co-creation", why:"Audience involvement = ownership feeling = stronger loyalty and shares." },
  { id:28, title:"Mere saath ek din — content kaise banta hai?", category:"Sales", format:"Mini Doc", hook:"Script se shoot tak — yeh sab 18 ghante mein hota hai.", angle:"Behind the scenes access", why:"BTS content humanizes the creator and builds deeper connection with process-curious audience." },
  { id:29, title:"Yeh hai meri research process — copy karo", category:"Sales", format:"Explainer", hook:"Main fake news se aise bachta hoon — step by step.", angle:"Skill share + authority", why:"Teaching your process positions you as expert and attracts creators as audience." },
  { id:30, title:"2025 mein main yeh nahi karunga — creator boundaries", category:"Sales", format:"Talking Head", hook:"Kuch topics hain jo main nahi chhunuunga. Reason jaante ho?", angle:"Values-based positioning", why:"Showing what you stand against is as powerful as showing what you stand for." },
];
